### ISSUE TITLE
Better terminal support

### ISSUE THREAD

**Issue by jssee** [mswift42/reykjavik-theme#3]
I really love this theme, ive made ports of it to sublime and vscode but now that im using spacemacs via iTerm, I'm noticing its not rendering very good. I think a good solution would be to check if GUI emacs is running, and if not, set the background to `nil` like so: 

`(bg1 (if (display-graphic-p) "#292a44" nil)) ;; default background`

I've seen this used successfully on other themes, and I think it'd be great to use here. not to mention, the other themes like soft-morning and white-sand 😉

**Comment by mswift42** [comment]
Have you tried it with this change ? Does it work for you then?

**Comment by jssee** [comment]
Yes, i tested this by adding this into the theme file: 

`(bg1 (if (display-graphic-p) "#112328" nil))`

and it works for me on terminal. here is where i put it for reference:

```lisp
 (deftheme reykjavik)
 (let ((class '((class color) (min-colors 89)))
       (fg1 "#b1b1b1")
       (fg2 "#a3a3a3")
       (fg3 "#959595")
       (fg4 "#878787")
       (bg1 (if (display-graphic-p) "#112328" nil))
       (bg2 "#243539")
       (bg3 "#37464a")
       (bg4 "#4a585c")
       (builtin "#c4cbee")
       (keyword "#a3d4e8")
       (const   "#a3d6cc")
       (comment "#5d5d5d")
       (func    "#f1c1bd")
       (str     "#e6c2db")
       (type    "#c1d2b1")
       (var     "#e1c9aa")
       (warning "#e81050")
       (warning2 "#e86310"))
 ```
edit: i havent test what happens when running in a GUI, only terminal

**Comment by mswift42** [comment]
Thanks, it still works when using gui.

**Comment by jssee** [comment]
Thanks!
